# Generated by Django 3.0.5 on 2020-04-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序列号')),
                ('uname', models.CharField(max_length=200, verbose_name='账号')),
                ('mima', models.CharField(max_length=12, verbose_name='密码')),
                ('dianhua', models.CharField(max_length=11, verbose_name='电话号码')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'user',
            },
        ),
    ]
